version: 2
jobs:
  build:

    branches:
      only:
        - master 

    docker:
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:

      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
         name: install openmpi
         command: |
            sudo apt-get update && sudo apt-get install libopenmpi-dev openmpi-common openmpi-bin vtk6 libvtk6-dev

      - run:
          name: install PyGran deps
          command: |
            pip3 install -e .[extra] --user

      - run:
          name: compile LIGGGHTS
          command: |
            python3 setup.py build_liggghts

      - run:
          name: install PyGran
          command: |
            pip3 install . --user

      - run:
          name: run tests
          command: |
            python3 -m pytest --cov src/PyGran tests/pytest/test_sim --mpath tests/pytest/test_sim
            python3 -m pytest --cov src/PyGran tests/pytest/test_analysis --trajf "DEM_flow/traj/particles*.dump"
            python3 -m codecov

      - store_test_results:
          path: .
